[phases.setup]
nixPkgs = ["xvfb", "chromium", "nss", "gtk3", "pango", "cairo", "xorg.libXcomposite", "xorg.libXdamage", "xorg.libXfixes", "xorg.libXrandr", "xorg.libX11", "alsa-lib", "libdrm", "mesa"]

[phases.install]
cmds = ["npm ci", "npx playwright install --with-deps chromium"]

[start]
cmd = "xvfb-run -a node worker.cjs"
